sudo: required
services:
  - docker

before_install:
  - docker build -t marci/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run marci/react-test npm test -- --coverage

after_success:
  - docker build -t marci/multi-client ./client
  - docker build -t marci/multi-nginx ./nginx
  - docker build -t marci/multi-server ./server
  - docker build -t marci/multi-worker ./worker