sudo: required
services:
  - docker

before_install:
  - docker build -t marcelino13/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true marcelino13/react-test npm test

after_success:
  - docker build -t marcelino13/multi-client ./client
  - docker build -t marcelino13/multi-nginx ./nginx
  - docker build -t marcelino13/multi-server ./server
  - docker build -t marcelino13/multi-worker ./worker
  # log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push marcelino13/multi-client
  - docker push marcelino13/multi-nginx
  - docker push marcelino13/multi-server
  - docker push marcelino13/multi-worker
